baseURL = 'https://cjauvin.github.io/inf1901-teluq-hugo/'
languageCode = 'fr'
defaultContentLanguage = 'fr'
canonifyURLs = true

title = "INF 1901 - Introduction à l'intelligence artificielle"
theme = 'hugo-book'

# --- Paramètres du thème hugo-book ---
[params]
BookMenuBundle = "book"
BookTheme = "auto"
BookToC = true
BookSearch = true
javaRunnerEndpoint = "http://localhost:5123/run"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]