baseURL = 'https://cjauvin.github.io/inf1901-teluq/'
languageCode = 'fr'
defaultContentLanguage = 'fr'
canonifyURLs = true

title = "INF1901 - Initiation à l'IA : concepts et réflexions"
theme = 'hugo-book-teluq'

# --- Paramètres du thème hugo-book ---
[params]
BookMenuBundle = "book"
BookTheme = "auto"
BookToC = true
BookSearch = false
BookNav = true
BookLogo = "images/paperclip-logo.png"
BookFavicon = "images/paperclip-logo.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4